# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasure.Answer'),
        ),
    ]
