# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0004_auto_20170927_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='solved',
            field=models.IntegerField(default=0),
        ),
    ]
