# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0005_userprofile_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='url',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
