# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0006_question_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
