# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasure', '0008_auto_20170927_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solved_by',
            field=models.ManyToManyField(blank=True, related_name='wings', to=settings.AUTH_USER_MODEL),
        ),
    ]
