# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0011_bonusquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusquestion',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bonusquestion',
            name='url',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.IntegerField(null=True),
        ),
    ]
