# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0013_auto_20171005_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusquestion',
            name='desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
