# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0015_question_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
