# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0018_auto_20171005_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusquestion',
            name='desc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
