# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasure', '0020_auto_20171006_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasuQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(unique=True)),
                ('url', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('image', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, max_length=20000, null=True)),
                ('desc', models.TextField(blank=True, max_length=100, null=True)),
                ('points', models.IntegerField(default=0, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('released', models.BooleanField(default=False)),
                ('solved_by', models.ManyToManyField(blank=True, related_name='basu_wings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
