# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0021_basuquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basuquestion',
            old_name='correct_answer',
            new_name='correct_answer1',
        ),
        migrations.AddField(
            model_name='basuquestion',
            name='correct_answer2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
