# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0022_auto_20171006_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basuquestion',
            old_name='correct_answer1',
            new_name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='basuquestion',
            name='correct_answer2',
        ),
    ]
